### ISSUE TITLE
1. Provide all necessary tools for project

### ISSUE THREAD

**Issue by alltestgreen** [TestardR/geo-port#1]
Hi Romain,

Thank you for taking the time to complete our test and to agree to provide some improvements.
This is entire part of the interview process.

There are no time constraints from my side, so you can provide fixes and/or discussion on your own time, at your own pace.

Dependencies are not installed automatically. Would be nice if `make deps` or similar command would prepare all required dependencies such as `ginkgo` on any environment.

Running `make test` results missing library:
```
Running tests ...
make: ginkgo: No such file or directory
make: *** [Makefile:17: test] Error 127
```

As of using third party tools, it would be also nice if the project is ready for linting by just a make command.

**Comment by TestardR** [comment]
Hi Attila, 

Thank you for the follow up.

Good catch.

- Regarding ginkgo third party dependency, I have made sure that `make deps` installs ginkgo binary locally, so that developers can run tests easily. After running `make deps`, `make test` should run properly.

- Regarding linting using golangci-lint (https://github.com/golangci/golangci-lint), I have added a `make lint` command.
Installing golangci-lint locally depends on the developers machine, as such I added an entry in README.md.
