### ISSUE TITLE
2. Unexported types returned by exported functions

### ISSUE THREAD

**Issue by alltestgreen** [TestardR/geo-port#2]
Can you please explain the decision behind retuning unexported type in exported functions such as `NewPortService` and `NewCoordinates`?

**Comment by TestardR** [comment]
Unexported types returned by exported functions is a convention I have developed with my current team on a big Go project.

- It reduces developers cognitive load on how to instanciate structs by enforcing instanciation through named constructor (there is one way to instantiate).
- It gives the codebase more homogeniety as the team idiom is applied throughout the codebase.
- It forces developers to think about why types/properties should be made public rather than having everything exportable.

It's a convention, I have found it useful. Is it a necessity ? I would say no. However, on big Go projects with new joiners (not necessarily Go experts), it has come handy.
