### ISSUE TITLE
4. Multi staged docker build

### ISSUE THREAD

**Issue by alltestgreen** [TestardR/geo-port#4]
Could you please add another stage to dockerfile so final image would be nothing but necessary executables?

**Comment by TestardR** [comment]
I have rewritten the Dockerfile so that it is multistaged. The first builds the binary, the second stage (so the final image) only holds necessary executable.

This was a very good call. I used the `FROM scratch` directive, which builds a final image of 5.28MB instead of 227MB with golang:alpine. Pretty neat gain.

Note: The assignment was suggesting to avoid code building in docker. Still, I went for building the code in docker as you suggested using a multi staged docker build. By industry standard, the first stage is dedicated to build.
